page:
  form:
    title: 用户信息
    content:
      - { type: "input", name: "username", required: true, col: 8 }
      - { type: "password", name: "password", required: true, col: 8 }
      - {
          type: "checkbox",
          name: "likes",
          required: true,
          col: 8,
          items: [{ lable:'羽毛球', value: 1 }, { lable:'乒乓球', value: 2 }],
        }
      - {
          type: "radio",
          name: "sex",
          required: true,
          col: 8,
          items: [{ lable:'男', value: 0 }, { lable:'女', value: 1 }],
        }
      - {
          type: "select",
          name: "sex",
          required: true,
          col: 8,
          items:
            [
              { lable:'Lucy', value: "Lucy" },
              { lable:'Jack', value: "Jack" },
              { lable:'Jack2', value: "Jack2" },
            ],
        }
    submit:
      btns:
        - { type: "submit", label: "submit", action: "/action.do" }
        - { type: "reset", label: "reset" }
